export const customOrder = {
  'Investigador Principal': 1,
  'Investigadora Principal': 2,
  'Investigador Clínico Principal': 3,
  'Investigadora Clínica Principal': 4,
  'Investigador Independiente': 5,
  'Investigadora Independiente': 6,
  'Investigador Clínico Independiente': 7,
  'Investigadora Clínica Independiente': 8,
  'Investigador Adjunto': 9,
  'Investigadora Adjunta': 10,
  'Investigador Clínico Adjunto': 11,
  'Investigadora Clínica Adjunta': 12,
  'Investigador Asistente': 13,
  'Investigadora Asistente': 14,
  'Investigador Externo': 15,
  'Investigadora Externa': 16,
  'Becario PosDoctoral': 17,
  'Becaria PosDoctoral': 18,
  'Becario Doctoral': 19,
  'Becaria Doctoral': 20,
  'Becario Externo': 21,
  'Becaria Externa': 22,
  'Profesional Principal': 23,
  'Profesional Adjunto': 24,
  'Profesional Adjunta': 25,
  'Profesional Asistente': 26,
  'Técnico Principal': 27,
  'Técnica Principal': 28,
  'Técnico Asistente': 29,
  'Técnica Asistente': 30,
};